// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcdwdriwnnyejpwceezq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZHdkcml3bm55ZWpwd2NlZXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDI0MDYsImV4cCI6MjA2NDc3ODQwNn0.w5p_3_ERu6hVjwXpDozAz6Zyl5PrR8Sz08SNUMreSnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);