// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izmeuvoiufrbauisotym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6bWV1dm9pdWZyYmF1aXNvdHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDY0MDgsImV4cCI6MjA2NDg4MjQwOH0.g0gQVSw6QV9Y70HQ85nkvfN1M07i0tNLTLDtfqXfWrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);